from setuptools import setup, find_packages

setup(
    name="hr-automation-platform",
    version="1.0.0",
    description="Enterprise HR Automation Platform",
    author="HR Platform Team",
    author_email="team@hrplatform.com",
    packages=find_packages(),
    python_requires=">=3.11",
    install_requires=[
        "fastapi==0.104.1",
        "uvicorn[standard]==0.24.0",
        "sqlalchemy==2.0.23",
        "asyncpg==0.29.0",
        "pydantic==2.5.0",
        "pydantic-settings==2.1.0",
        "python-dotenv==1.0.0",
        "python-jose[cryptography]==3.3.0",
        "passlib[bcrypt]==1.7.4",
        "bcrypt==4.1.1",
        "alembic==1.12.1",
        "redis==5.0.1",
        "aio-pika==9.0.10",
        "python-multipart==0.0.6",
        "httpx==0.25.2",
        "requests==2.31.0",
        "boto3==1.34.5",
        "sendgrid==6.10.0",
        "openai==1.3.10",
        "anthropic==0.7.10",
        "elasticsearch==8.11.0",
        "elasticsearch-dsl==8.11.0",
        "python-json-logger==2.0.7",
        "pytz==2023.3",
        "email-validator==2.1.0",
    ],
    extras_require={
        "dev": [
            "pytest==7.4.3",
            "pytest-asyncio==0.21.1",
            "pytest-cov==4.1.0",
            "black==23.12.0",
            "flake8==6.1.0",
            "mypy==1.7.1",
        ]
    },
)
